spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kamaji-webhook-service
          namespace: kamaji-system
          path: /convert
      conversionReviewVersions:
        - v1
