version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    rebase-strategy: disabled
    commit-message:
      prefix: "feat(deps)"
    groups:
      k8s:
        patterns:
          - "k8s.io*"
      etcd:
        patterns:
          - "go.etcd.io/etcd/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    rebase-strategy: disabled
    commit-message:
      prefix: "chore(ci)"
