linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/clastix/kamaji)
  goheader:
    template: |-
      Copyright 2022 Clastix Labs
      SPDX-License-Identifier: Apache-2.0

linters:
  disable:
    - wrapcheck
    - gomnd
    - scopelint
    - golint
    - interfacer
    - maligned
    - varnamelen
    - testpackage
    - tagliatelle
    - paralleltest
    - ireturn
    - goerr113
    - gochecknoglobals
    - exhaustivestruct
    - wsl
    - exhaustive
    - nosprintfhostport
    - nonamedreturns
    - interfacebloat
    - exhaustruct
    - lll
    - gosec
    - gomoddirectives
    - godox
    - gochecknoinits
    - funlen
    - dupl
    - maintidx
    - cyclop
  enable-all: true
