run:
  timeout: 10m

linters-settings:
  revive:
    rules:
      - name: dot-imports
        arguments:
          - allowedPackages:
              - "github.com/onsi/ginkgo/v2"
              - "github.com/onsi/gomega"
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/clastix/kamaji/)
  goheader:
    template: |-
      Copyright 2022 Clastix Labs
      SPDX-License-Identifier: Apache-2.0

linters:
  disable:
    - depguard
    - wrapcheck
    - mnd
    - varnamelen
    - testpackage
    - tagliatelle
    - paralleltest
    - ireturn
    - err113
    - gochecknoglobals
    - wsl
    - exhaustive
    - nosprintfhostport
    - nonamedreturns
    - interfacebloat
    - exhaustruct
    - lll
    - gosec
    - gomoddirectives
    - godox
    - gochecknoinits
    - funlen
    - dupl
    - cyclop
    - gocognit
    - nestif
    - perfsprint
    # deprecated linters
    - exportloopref
  enable-all: true
