# permissions for end users to view datastores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datastore-viewer-role
rules:
- apiGroups:
  - kamaji.clastix.io
  resources:
  - datastores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kamaji.clastix.io
  resources:
  - datastores/status
  verbs:
  - get
