# permissions for end users to view clusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantcontrolplane-viewer-role
rules:
- apiGroups:
  - kamaji.clastix.io
  resources:
  - tenantcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kamaji.clastix.io
  resources:
  - tenantcontrolplanes/status
  verbs:
  - get
