# Metal LB manifests: used for local development purposes
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kamaji-kind-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.19.255.100-172.19.255.150
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
