#cloud-config
package_upgrade: true
packages:
  - containerd
  - apt-transport-https
  - ca-certificates
  - curl
write_files:
  - owner: root:root
    path: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
  - owner: root:root
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
runcmd:
  - sudo modprobe overlay
  - sudo modprobe br_netfilter
  - sudo sysctl --system
  - sudo mkdir -p /etc/containerd
  - containerd config default | sed -e 's#SystemdCgroup = false#SystemdCgroup = true#g' | sudo tee -a /etc/containerd/config.toml
  - sudo systemctl restart containerd
  - sudo systemctl enable containerd
  - sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - sudo apt update
  - sudo apt install -y kubelet=1.23.5-00 kubeadm=1.23.5-00 kubectl=1.23.5-00
  - sudo apt-mark hold kubelet kubeadm kubectl