- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: '{{ include "kamaji.webhookServiceName" . }}'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-kamaji-clastix-io-v1alpha1-tenantcontrolplane
  failurePolicy: Fail
  name: mtenantcontrolplane.kb.io
  rules:
    - apiGroups:
        - kamaji.clastix.io
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - tenantcontrolplanes
  sideEffects: None
