apiVersion: kamaji.clastix.io/v1alpha1
kind: TenantControlPlane
metadata:
  name: additional-volumes
  labels:
    tenant.clastix.io: additional-volumes
spec:
  controlPlane:
    deployment:
      replicas: 1
      additionalVolumes:
        - name: api-server-volume
          configMap:
            name: api-server-extra-cm
        - name: controller-manager-volume
          configMap:
            name: controller-manager-extra-cm
        - name: scheduler-volume
          configMap:
            name: scheduler-extra-cm
      additionalVolumeMounts:
        apiServer:
          - name: api-server-volume
            mountPath: "/tmp/api-server"
        controllerManager:
          - name: controller-manager-volume
            mountPath: "/tmp/controller-manager"
        scheduler:
          - name: scheduler-volume
            mountPath: "/tmp/scheduler"
    service:
      serviceType: LoadBalancer
  kubernetes:
    version: "v1.26.0"
    kubelet:
      cgroupfs: systemd
  networkProfile:
    port: 6443
  addons:
    coreDNS: {}
    kubeProxy: {}
---
apiVersion: v1
data:
  api-server: "This is an API Server volume"
kind: ConfigMap
metadata:
  name: api-server-extra-cm
---
apiVersion: v1
data:
  controller-manager: "This is a Controller Manager volume"
kind: ConfigMap
metadata:
  name: controller-manager-extra-cm
---
apiVersion: v1
data:
  controller-manager: "This is a Scheduler volume"
kind: ConfigMap
metadata:
  name: scheduler-extra-cm
