apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: postgresql-bronze
spec:
  driver: PostgreSQL
  endpoints:
    - postgres-bronze-rw.postgres-system.svc:5432
  basicAuth:
    username:
      secretReference:
        name: postgres-bronze-superuser
        namespace: postgres-system
        keyPath: username
    password:
      secretReference:
        name: postgres-bronze-superuser
        namespace: postgres-system
        keyPath: password
  tlsConfig:
    certificateAuthority:
      certificate:
        secretReference:
          name: postgres-bronze-ca
          namespace: postgres-system
          keyPath: ca.crt
    clientCertificate:
      certificate:
        secretReference:
          name: postgres-bronze-root-cert
          namespace: postgres-system
          keyPath: tls.crt
      privateKey:
        secretReference:
          name: postgres-bronze-root-cert
          namespace: postgres-system
          keyPath: tls.key
