apiVersion: kamaji.clastix.io/v1alpha1
kind: TenantControlPlane
metadata:
  name: konnectivity-addon
  labels:
    tenant.clastix.io: konnectivity-addon
spec:
  deployment:
    replicas: 2
  service:
    serviceType: LoadBalancer
  kubernetes:
    version: "v1.26.0"
    kubelet:
      cgroupfs: systemd
  networkProfile:
    port: 6443
  addons:
    coreDNS: {}
    kubeProxy: {}
    konnectivity:
      server:
        port: 8132
