apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: postgresql-gold
spec:
  driver: PostgreSQL
  endpoints:
    - postgres-gold-rw.postgres-system.svc:5432
  basicAuth:
    username:
      secretReference:
        name: postgres-gold-superuser
        namespace: postgres-system
        keyPath: username
    password:
      secretReference:
        name: postgres-gold-superuser
        namespace: postgres-system
        keyPath: password
  tlsConfig:
    certificateAuthority:
      certificate:
        secretReference:
          name: postgres-gold-ca
          namespace: postgres-system
          keyPath: ca.crt
    clientCertificate:
      certificate:
        secretReference:
          name: postgres-gold-root-cert
          namespace: postgres-system
          keyPath: tls.crt
      privateKey:
        secretReference:
          name: postgres-gold-root-cert
          namespace: postgres-system
          keyPath: tls.key
