apiVersion: kamaji.clastix.io/v1alpha1
kind: TenantControlPlane
metadata:
  name: tenant1
spec:
  controlPlane:
    deployment:
      replicas: 2
      additionalMetadata:
        annotations:
          environment.clastix.io: test
          tier.clastix.io: "0"
        labels:
          tenant.clastix.io: test
          kind.clastix.io: deployment
    service:
      additionalMetadata:
        annotations:
          environment.clastix.io: test
          tier.clastix.io: "0"
        labels:
          tenant.clastix.io: test
          kind.clastix.io: service
      serviceType: NodePort
    ingress:
      enabled: false
  kubernetes:
    version: "v1.23.4"
    kubelet:
      cgroupfs: cgroupfs
    admissionControllers:
    - LimitRanger
    - ResourceQuota
  networkProfile:
    address: "172.18.0.2"
    port: 31443
    domain: "clastix.labs"
    serviceCidr: "10.96.0.0/16"
    podCidr: "10.244.0.0/16"
    dnsServiceIPs: 
    - "10.96.0.10"
  addons:
    konnectivity:
      proxyPort: 31132
      proxyHost: "172.18.0.2"
      version: v0.0.31
    coreDNS: {}
    kubeProxy:
