config:
  merge:
    accounts:
      private:
        jetstream: enabled
        users:
        - {user: admin, password: "password", permissions: {subscribe: [">"], publish: [">"]}}
  cluster:
    enabled: no
  nats:
    tls:
      enabled: true
      secretName: nats-$NAME-config
      cert: server.crt
      key: server.key
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 32Mi
