{{- $issuerRef := (.Values.certManager | default dict).issuerRef | default dict }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- $data := . | mustMergeOverwrite (dict "component" "certificate") -}}
    {{- include "kamaji.labels" $data | nindent 4 }}
  name: {{ include "kamaji.certificateName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ include "kamaji.webhookServiceName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kamaji.webhookServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: {{ $issuerRef.kind | default "Issuer" | quote }}
    name: {{ $issuerRef.name | default "kamaji-selfsigned-issuer" | quote }}
    group: {{ $issuerRef.group | default "cert-manager.io" | quote }}
  secretName: {{ include "kamaji.webhookSecretName" . }}
