{{- $issuerRef := (.Values.certManager | default dict).issuerRef | default dict }}
{{- $issuerName := "kamaji-selfsigned-issuer" }}
{{- $issuerKind := "Issuer" }}
{{- $issuerGroup := "cert-manager.io" }}
{{- if $issuerRef.name }}
{{- $issuerName = $issuerRef.name }}
{{- $issuerKind = $issuerRef.kind | default $issuerKind }}
{{- $issuerGroup = $issuerRef.group | default $issuerGroup }}
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- $data := . | mustMergeOverwrite (dict "component" "certificate") -}}
    {{- include "kamaji.labels" $data | nindent 4 }}
  name: {{ include "kamaji.certificateName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ include "kamaji.webhookServiceName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kamaji.webhookServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: {{ $issuerKind | quote }}
    name: {{ $issuerName | quote }}
    group: {{ $issuerGroup | quote }}
  secretName: {{ include "kamaji.webhookSecretName" . }}
