apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kamaji.certificateName" . }}
  labels:
    {{- include "kamaji.labels" . | nindent 4 }}
    app.kubernetes.io/instance: mutating-webhook-configuration
  name: kamaji-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kamaji.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-kamaji-clastix-io-v1alpha1-datastore
    failurePolicy: Fail
    name: mdatastore.kb.io
    rules:
      - apiGroups:
          - kamaji.clastix.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - datastores
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kamaji.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-kamaji-clastix-io-v1alpha1-tenantcontrolplane
    failurePolicy: Fail
    name: mtenantcontrolplane.kb.io
    rules:
      - apiGroups:
          - kamaji.clastix.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - tenantcontrolplanes
    sideEffects: None