apiVersion: v1
kind: Service
metadata:
  name: {{ include "kamaji.fullname" . }}
  labels:
    {{- include "kamaji.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: https
  selector:
    {{- include "kamaji.selectorLabels" . | nindent 4 }}
