apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kamaji.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  name: {{ include "kamaji.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8080
      name: metrics
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "kamaji.selectorLabels" . | nindent 4 }}
