name: Check PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  semantic-pr-title:
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
